name: measure_startup_time
description: "Flutter package for measuring the startup time of a Flutter web application."
version: 0.0.1
homepage: https://github.com/DiemUyen/measure_startup_time

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MeasureStartupTimeWeb
        fileName: measure_startup_time_web.dart
